modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Lothrazar/Similsax-Transtructors/issues"
license="zlib"

[[mods]]
modId="similsaxtranstructors"
version="${file.jarVersion}"
displayName="Similsax Transtructors - Builder's Wands"
updateJSONURL="https://raw.githubusercontent.com/Lothrazar/Similsax-Transtructors/trunk/1.20/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/similsax-transtructors"
authors="Lothrazar, Vorquel"
description='''
Simple classic building tools for long range structures
'''
[[dependencies.similsaxtranstructors]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,]"
ordering="NONE"
side="BOTH"
[[dependencies.similsaxtranstructors]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.similsaxtranstructors]]
    modId="flib"
    mandatory=true
    versionRange="[0.0.7,)"
    ordering="NONE"
    side="BOTH"