modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/Lothrazar/Similsax-Transtructors/issues"
license="zlib"

[[mods]]
modId="similsaxtranstructors"
version="${file.jarVersion}"
displayName="Similsax Transtructors - Builder's Wands"
updateJSONURL="https://raw.githubusercontent.com/Lothrazar/Similsax-Transtructors/master/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/similsax-transtructors"
authors="Lothrazar, Vorquel"
description='''
Simple classic building tools for long range structures
'''
[[dependencies.similsaxtranstructors]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3,]"
ordering="NONE"
side="BOTH"
[[dependencies.similsaxtranstructors]]
modId="forge"
mandatory=true
versionRange="[44.0.6,)"
ordering="NONE"
side="BOTH"