modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Lothrazar/Similsax-Transtructors/issues"
license="zlib"

[[mods]]
modId="similsaxtranstructors"
version="${file.jarVersion}"
displayName="Similsax Transtructors - Builder's Wands"
updateJSONURL="https://raw.githubusercontent.com/Lothrazar/Similsax-Transtructors/trunk/1.20/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/similsax-transtructors"
authors="Lothrazar, Vorquel"
description='''
Simple classic building tools for long range structures
'''
[[dependencies.similsaxtranstructors]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.similsaxtranstructors]]
modId="neoforge"
type="required"
versionRange="[21.1.1,]"
ordering="NONE"
side="BOTH"